### PR TITLE
Laravel 5.4 support

### PR DESCRIPTION
**Pull request by jandub**
I replaced the removed share method with the singleton method to make the package Laravel 5.4 compatible (https://laravel.com/docs/5.4/upgrade). I'm not too familiar with the package, but it seems to work fine in our project.

### CODE REVIEW

**Comment by FaCuZ** [comment]
Please, merge this pull request!

**Comment by vijaythecoder** [comment]
There is one more problem coming with up `5.4` update,  
```
Illegal offset type in unset
```
This comes from ThemeServiceProvider.php

**Comment by jandub** [comment]
@vijaythecoder can you be more specific, please? How can I reproduce it?

**Comment by vijaythecoder** [comment]
image

Solution:
```php
$this->app['asset'] = $this->app->singleton(function($app) 
```
should be 

```php
$this->app->singleton('asset', function ($app) {
```
This should be repeated to every method in ThemeServiceProvider.php file and then it works.  @jandub

**Pull request closed without merging**
